/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { InfractionType } from '../types';

// Raw infractions list pipe-separated: code|description|framing|nature|score
const RAW_INFRACTIONS: string[] = [
  "751-01|Iniciar obra perturbe/interrompa circulação/segurança veíc/pedestre s/permissão.|Art. 95.|Leve|0",
  "751-02|Iniciar evento perturbe/interrompa circulação/segurança veíc/pedestre s/permissão.|Art. 95.|Leve|0",
  "752-81|Não sinalizar a execução ou manutenção da obra.|Art. 95, §1º.|Leve|0",
  "752-82|Não sinalizar a execução ou manutenção do evento.|Art. 95, §1º.|Leve|0",
  "501-00|Dirigir veículo sem possuir CNH, PPD ou ACC.|Art. 162, I.|Gravíssima|7",
  "502-91|Dirigir veículo com CNH, PPD ou ACC cassada.|Art. 162, II.|Gravíssima|7",
  "502-92|Dirigir veículo com CNH, PPD ou ACC com suspensão do direito de dirigir.|Art. 162, II.|Gravíssima|7",
  "503-71|Dirigir veículo com CNH de categoria diferente da do veículo.|Art. 162, III.|Gravíssima|7",
  "503-72|Dirigir veículo com PPD de categoria diferente da do veículo.|Art. 162, III.|Gravíssima|7",
  "504-50|Dirigir veículo com validade de CNH vencida há mais de 30 dias.|Art. 162, V.|Gravíssima|7",
  "505-31|Dirigir veículo sem usar lentes corretoras de visão.|Art. 162, VI.|Gravíssima|7",
  "505-32|Dirigir veículo sem usar aparelho auxiliar de audição.|Art. 162, VI.|Gravíssima|7",
  "505-33|Dirigir veículo sem usar aparelho auxiliar de prótese física.|Art. 162, VI.|Gravíssima|7",
  "505-34|Dirigir veículo s/ adaptações impostas na concessão/renovação licença conduzir.|Art. 162, VI.|Gravíssima|7",
  "774-91|Dirigir veículo sem possuir cursos especializados obrigatórios.|Art. 162, VII.|Gravíssima|7",
  "774-92|Dirigir veículo sem possuir cursos específicos obrigatórios.|Art. 162, VII.|Gravíssima|7",
  "506-10|Entregar veículo a pessoa sem CNH, PPD ou ACC.|Art. 163 c/c 162, I.|Gravíssima|7",
  "507-01|Entregar veículo a pessoa com CNH, PPD ou ACC Cassada.|Art. 163 c/c 162, II.|Gravíssima|7",
  "507-02|Entregar veículo a pessoa com CNH, PPD ou ACC com Suspensão do Direito de Dirigir.|Art. 163 c/c 162, II.|Gravíssima|7",
  "508-81|Entregar veículo a pessoa com CNH de categoria diferente da do veículo.|Art. 163 c/c 162, III|Gravíssima|7",
  "508-82|Entregar veículo a pessoa com PPD de categoria diferente da do veículo.|Art. 163 c/c 162, III.|Gravíssima|7",
  "509-60|Entregar veículo a pessoa com CNH vencida há mais de 30 dias.|Art. 163 c/c 162, V.|Gravíssima|7",
  "510-01|Entregar o veículo a pessoa sem usar lentes corretoras de visão.|Art. 163 c/c 162, VI.|Gravíssima|7",
  "510-02|Entregar o veículo a pessoa sem usar aparelho auxiliar de audição.|Art. 163 c/c 162, VI.|Gravíssima|7",
  "510-03|Entregar o veículo a pessoa sem aparelho de prótese física.|Art. 163 c/c 162, VI.|Gravíssima|7",
  "510-04|Entregar veíc pessoa s/ adaptações impostas concessão/renovação licença conduzir.|Art. 163 c/c 162, VI.|Gravíssima|7",
  "777-31|Entregar veículo a pessoa sem possuir cursos especializados obrigatórios.|Art. 163 c/c 162, VII.|Gravíssima|7",
  "777-32|Entregar veículo a pessoa sem possuir cursos específicos obrigatórios.|Art. 163 c/c 162, VII.|Gravíssima|7",
  "511-80|Permitir posse e condução do veículo a pessoa sem CNH, PPD ou ACC.|Art. 164 c/c 162, I.|Gravíssima|7",
  "512-61|Permitir posse e condução do veículo à pessoa com CNH, PPD ou ACC Cassada.|Art. 164 c/c 162, II.|Gravíssima|7",
  "512-62|Permitir posse/condução do veículo a pessoa com CNH, PPD ou ACC c/ susp. direito de dirigir.|Art. 164 c/c 162, II.|Gravíssima|7",
  "513-41|Permitir posse e condução do veículo a pessoa com CNH de categoria diferente da do veículo.|Art. 164 c/c 162, III.|Gravíssima|7",
  "513-42|Permitir posse e condução do veículo à pessoa com PPD de categoria diferente da do veículo.|Art. 164 c/c 162, III.|Gravíssima|7",
  "514-20|Permitir posse e condução do veículo à pessoa com CNH vencida há mais de 30 dias.|Art. 164 c/c 162, V.|Gravíssima|7",
  "515-01|Permitir posse e condução do veículo a pessoa sem usar lentes corretoras de visão.|Art. 164 c/c 162, VI.|Gravíssima|7",
  "515-02|Permitir posse e condução do veículo a pessoa sem usar aparelho auxiliar de audição.|Art. 164 c/c 162, VI.|Gravíssima|7",
  "515-03|Permitir posse/condução do veículo à pessoa sem usar aparelho de prótese física.|Art. 164 c/c 162, VI.|Gravíssima|7",
  "515-04|Permitir posse/cond veíc. s/ adaptações impostas concessão/renovação licença cond.|Art. 164 c/c 162, VI.|Gravíssima|7",
  "778-11|Permitir posse e condução do veículo à pessoa sem possuir cursos especializados obrigatórios.|Art. 164 c/c 162, VII.|Gravíssima|7",
  "778-12|Permitir posse e condução do veículo à pessoa sem possuir cursos específicos obrigatórios.|Art. 164 c/c 162, VII.|Gravíssima|7",
  "516-91|Dirigir sob a influência de álcool.|Art. 165.|Gravíssima|7",
  "516-92|Dirigir sob influência de substância psicoativa que determine dependência.|Art. 165.|Gravíssima|7",
  "757-90|Rec sub test, ex clin, peric ou proc q perm cert infl álc/sub psic for art. 277.|Art. 165-A.|Gravíssima|7",
  "764-10|Cond veíc exig hab C, D ou E sem realizar ex toxic prev no § 2º do art 148-A, após 30 dias do venc.|Art. 165-B.|Gravíssima|7",
  "765-00|Exerc at rem veíc e não compr a real ex toxic per ex p § 2º do art 148-A por oc ren hab C, D ou E|Art. 165-B, parágrafo único.|Gravíssima|7",
  "517-70|Confiar/entregar veíc pess c/estado físico/psíquico s/ condições dirigir segur.|Art. 166.|Gravíssima|7",
  "518-51|Deixar o condutor de usar o cinto de segurança.|Art. 167.|Grave|5",
  "518-52|Deixar o passageiro de usar o cinto de segurança.|Art. 167.|Grave|5",
  "519-30|Transportar criança sem observância das normas de segurança estabelecidas p/ CTB.|Art. 168.|Gravíssima|7",
  "520-70|Dirigir sem atenção ou sem os cuidados indispensáveis à segurança.|Art. 169.|Leve|3",
  "521-51|Dirigir ameaçando os pedestres que estejam atravessando a via pública.|Art. 170.|Gravíssima|7",
  "521-52|Dirigir ameaçando os demais veículos.|Art. 170.|Gravíssima|7",
  "522-31|Usar veículo para arremessar sobre os pedestres água ou detritos.|Art. 171.|Média|4",
  "522-32|Usar veículo para arremessar sobre os veículos água ou detritos.|Art. 171.|Média|4",
  "523-11|Atirar do veículo objetos ou substâncias.|Art. 172.|Média|4",
  "523-12|Abandonar na via objetos ou substâncias.|Art. 172.|Média|4",
  "524-00|Disputar corrida.|Art. 173.|Gravíssima|7",
  "525-81|Promover na via competição sem permissão.|Art. 174.|Gravíssima|7",
  "525-82|Promover na via eventos organizados sem permissão.|Art. 174.|Gravíssima|7",
  "525-83|Promover na via exibição e demonstração de perícia em manobra de veículo s/perm.|Art. 174.|Gravíssima|7",
  "526-61|Participar na via como condutor em competição sem permissão.|Art. 174.|Gravíssima|7",
  "526-62|Participar na via como condutor em evento organizado, sem permissão.|Art. 174.|Gravíssima|7",
  "526-63|Participar como condutor exib/demonst perícia em manobra de veic, s/ permissão.|Art. 174.|Gravíssima|7",
  "527-41|Utiliz veíc demonst/exibir manobra perigosa mediante arrancada brusca.|Art. 175.|Gravíssima|7",
  "527-42|Utiliz veíc dem/exibir manob perig med derrap/frenag c/ desliz/arrast pneus.|Art. 175.|Gravíssima|7",
  "528-20|Deixar o cond envolvido em acidente, de prestar ou providenciar socorro à vítima.|Art. 176, I.|Gravíssima|7",
  "529-00|Deixar o cond envolvido em acid, de adotar provid p/ evitar perigo p/o trânsito.|Art. 176, II.|Gravíssima|7",
  "530-40|Deixar o cond envolvido em acidente de preservar local p/ trab polícia/perícia.|Art. 176, III.|Gravíssima|7",
  "531-20|Deixar o cond envolvido em acid, de remover o veíc local qdo determ polic/agente.|Art. 176, IV.|Gravíssima|7",
  "532-00|Deixar o cond envolvido em acid, de identificar-se policial e prestar inf p/o BO.|Art. 176, V.|Gravíssima|7",
  "533-90|Deixar o cond de prestar socorro vítima acid de trânsito, qdo solicit p/ agente.|Art. 177.|Grave|5",
  "534-70|Deixar o condutor envolvido em acidente s/ vítima, de remover o veículo do local.|Art. 178.|Média|4",
  "535-50|Fazer ou deixar que se faça reparo em veíc, em rodovia e via de trânsito rápido.|Art. 179, I.|Grave|5",
  "536-30|Fazer/deixar que se faça reparo em veíc nas vias (q não rodovia/trânsito rápido)|Art. 179, II|Leve|3",
  "537-10|Ter seu veículo imobilizado na via por falta de combustível.|Art. 180.|Média|4",
  "538-00|Estacionar nas esquinas e a menos de 5m do alinhamento da via transversal.|Art. 181, I.|Média|4",
  "539-80|Estacionar afastado da guia da calçada (meio-fio) de 50cm a 1m.|Art. 181, II|Leve|3",
  "540-10|Estacionar afastado da guia da calçada (meio-fio) a mais de 1m.|Art. 181, III.|Grave|5",
  "541-00|Estacionar em desacordo com as posições estabelecidas no CTB.|Art. 181, IV.|Média|4",
  "542-81|Estacionar na pista de rolamento das estradas.|Art. 181, V.|Gravíssima|7",
  "542-82|Estacionar na pista de rolamento das rodovias.|Art. 181, V.|Gravíssima|7",
  "542-83|Estacionar na pista de rolamento das vias de trânsito rápido.|Art. 181, V.|Gravíssima|7",
  "542-84|Estacionar na pista de rolamento das vias dotadas de acostamento.|Art. 181, V.|Gravíssima|7",
  "543-60|Estacionar junto/sobre hidrantes de incêndio, reg. de água/tampa de poço visit gal sub.|Art. 181, VI.|Média|4",
  "544-40|Estacionar nos acostamentos.|Art. 181, VII.|Leve|3",
  "545-21|Estacionar no passeio.|Art. 181, VIII.|Grave|5",
  "545-22|Estacionar sobre faixa destinada a pedestre.|Art. 181, VIII.|Grave|5",
  "545-23|Estacionar sobre ciclovia ou ciclofaixa.|Art. 181, VIII.|Grave|5",
  "545-24|Estacionar nas ilhas ou refúgios.|Art. 181, VIII.|Grave|5",
  "545-25|Estacionar ao lado ou sobre canteiro central/divisores de pista de rolamento.|Art. 181, VIII.|Grave|5",
  "545-26|Estacionar ao lado ou sobre marcas de canalização.|Art. 181, VIII.|Grave|5",
  "545-27|Estacionar ao lado ou sobre gramado ou jardim público.|Art. 181, VIII.|Grave|5",
  "546-00|Estacionar em guia de calçada rebaixada destinada à entrada/saída de veículos.|Art. 181, IX.|Média|4",
  "547-90|Estacionar impedindo a movimentação de outro veículo.|Art. 181, X.|Média|4",
  "548-70|Estacionar ao lado de outro veículo em fila dupla.|Art. 181, XI.|Grave|5",
  "549-50|Estacionar na área de cruzamento de vias.|Art. 181, XII.|Grave|5",
  "550-90|Estacionar no ponto de embarque/desembarque de passageiros de transporte coletivo.|Art. 181, XIII.|Média|4",
  "551-72|Estacionar nas pontes.|Art. 181, XIV.|Grave|5",
  "551-73|Estacionar nos túneis.|Art. 181, XIV.|Grave|5",
  "552-50|Estacionar na contramão de direção.|Art. 181, XV.|Média|4",
  "553-30|Estacionar aclive/declive ñ freado e sem calço segurança, PBT superior a 3500 kg.|Art. 181, XVI.|Grave|5",
  "554-11|Estacionar em desacordo com a regulamentação especificada pela sinalização.|Art. 181, XVII.|Grave|5",
  "554-12|Estacionar em desacordo com a regulamentação - estacionamento rotativo.|Art. 181, XVII.|Grave|5",
  "554-13|Estacionar em desacordo com a regulamentação - ponto ou vaga de táxi.|Art. 181, XVII.|Grave|5",
  "554-14|Estacionar em desacordo com a regulamentação - vaga de carga/descarga.|Art. 181, XVII.|Grave|5",
  "554-17|Estacionar em desacordo com a regulamentação - vaga de curta duração.|Art. 181, XVII.|Grave|5",
  "555-00|Estacionar em local/horário proibido especificamente pela sinalização.|Art. 181, XVIII.|Média|4",
  "556-80|Estacionar local/horário de estacionamento e parada proibidos pela sinalização.|Art. 181, XIX.|Grave|5",
  "762-51|Estacionar nas vagas reserv às pess c/ deficiência, s/ credencial.|Art. 181, XX.|Gravíssima|7",
  "762-52|Estacionar nas vagas reserv a idosos, s/ credencial.|Art. 181, XX.|Gravíssima|7",
  "557-60|Parar nas esquinas e a menos de 5m do bordo do alinhamento da via transversal.|Art. 182, I.|Média|4",
  "558-40|Parar afastado da guia da calçada (meio-fio) de 50cm a 1m.|Art. 182, II.|Leve|3",
  "559-20|Parar afastado da guia da calçada (meio-fio) a mais de 1m.|Art. 182, III.|Média|4",
  "560-60|Parar em desacordo com as posições estabelecidas no CTB.|Art. 182, IV.|Leve|3",
  "561-41|Parar na pista de rolamento das estradas.|Art. 182, V.|Grave|5",
  "561-42|Parar na pista de rolamento das rodovias.|Art. 182, V.|Grave|5",
  "561-43|Parar na pista de rolamento das vias de trânsito rápido.|Art. 182, V.|Grave|5",
  "561-44|Parar na pista de rolamento das demais vias dotadas de acostamento.|Art. 182, V.|Grave|5",
  "562-21|Parar no passeio.|Art. 182, VI.|Leve|3",
  "562-22|Parar sobre faixa destinada a pedestres.|Art. 182, VI.|Leve|3",
  "562-23|Parar nas ilhas ou refúgios.|Art. 182, VI.|Leve|3",
  "562-24|Parar nos canteiros centrais/divisores de pista de rolamento.|Art. 182, VI.|Leve|3",
  "562-25|Parar nas marcas de canalização.|Art. 182, VI.|Leve|3",
  "563-00|Parar na área de cruzamento de vias.|Art. 182, VII.|Média|4",
  "564-91|Parar nos viadutos.|Art. 182, VIII.|Média|4",
  "564-92|Parar nas pontes.|Art. 182, VIII.|Média|4",
  "564-93|Parar nos túneis.|Art. 182, VIII.|Média|4",
  "565-70|Parar na contramão de direção.|Art. 182, IX.|Média|4",
  "566-50|Parar em local/horário proibidos especificamente pela sinalização.|Art. 182, X.|Média|4",
  "767-00|Parar o veículo sobre ciclovia ou ciclofaixa.|Art. 182, XI.|Grave|5",
  "567-31|Parar sobre faixa de pedestres na mudança de sinal luminoso.|Art. 183.|Média|4",
  "568-10|Transitar na faixa/pista da direita regul circulação exclusiva determ veículo.|Art. 184, I.|Leve|3",
  "569-00|Transitar na faixa/pista da esquerda regul circulação exclusiva determ veículo.|Art. 184, II.|Grave|5",
  "758-70|Transitar na faixa ou via exclusiva regulam. p/transp. públ. coletivo passageiro.|Art. 184, III.|Gravíssima|7",
  "570-30|Deixar de conservar o veículo na faixa a ele destinada pela sinalização de regul.|Art. 185, I.|Média|4",
  "571-10|Deixar de conservar nas faixas da direita o veículo lento e de maior porte.|Art. 185, II.|Média|4",
  "572-00|Transitar pela contramão de direção em via com duplo sentido de circulação.|Art. 186, I.|Grave|5",
  "573-80|Transitar pela contramão de direção em via c/ sinalização de regul sentido único.|Art. 186, II.|Gravíssima|7",
  "574-61|Transitar em local/horário não permitido pela regul estabelecida p/autoridade.|Art. 187, I.|Média|4",
  "574-62|Transitar em local/horário não permitido pela regulamentação - Rodízio.|Art. 187, I.|Média|4",
  "574-63|Transitar em local/horário não permitido pela regulamentação - Caminhão.|Art. 187, I.|Média|4",
  "576-20|Transitar ao lado de outro veículo, interrompendo ou perturbando o trânsito.|Art. 188.|Média|4",
  "577-01|Deixar de dar passagem a veíc precedido de batedores devidamente identificados.|Art. 189.|Gravíssima|7",
  "577-02|Deixar de dar passagem a veíc socorro incêndio/salv serv urgência devid identif.|Art. 189.|Gravíssima|7",
  "577-03|Deixar de dar passagem a veíc de polícia em serviço de urgência devid identif.|Art. 189.|Gravíssima|7",
  "577-04|Deixar de dar passagem a veíc de operação e fiscalização de trânsito devid ident.|Art. 189.|Gravíssima|7",
  "577-05|Deixar de dar passagem a ambulância em serviço de urgência devid identificada.|Art. 189.|Gravíssima|7",
  "578-90|Seguir veículo em serv urgência devid identific p/ alarme sonoro/ilum.|Art. 190.|Grave|5",
  "579-70|Forçar passagem entre veícs trans sent opostos na iminência realiz ultrapassagem.|Art. 191.|Gravíssima|7",
  "580-00|Deixar guardar dist segurança lat/front entre seu veíc e demais e ao bordo pista.|Art. 192.|Grave|5",
  "581-91|Transitar com o veículo em calçadas, passeios.|Art. 193.|Gravíssima|7",
  "581-92|Transitar com o veículo em ciclovias, ciclofaixas.|Art. 193.|Gravíssima|7",
  "581-93|Transitar com o veículo em ajardinamentos, gramados e jardins públicos.|Art. 193.|Gravíssima|7",
  "581-94|Transitar com o veículo em canteiros centrais/divisores de pista de rolamento.|Art. 193.|Gravíssima|7",
  "581-95|Transitar com o veículo em ilhas, refúgios.|Art. 193.|Gravíssima|7",
  "581-96|Transitar com o veículo em marcas de canalização.|Art. 193.|Gravíssima|7",
  "581-97|Transitar com o veículo em acostamentos.|Art. 193.|Gravíssima|7",
  "581-98|Transitar com o veículo em passarelas.|Art. 193.|Gravíssima|7",
  "582-70|Transitar em marcha ré, salvo na distância necessária a pequenas manobras.|Art. 194.|Grave|5",
  "583-50|Desobedecer às ordens emanadas da autorid compet de trânsito ou de seus agentes.|Art. 195.|Grave|5",
  "584-31|Deixar de indicar c/antec, med gesto de braço/luz indicadora, início da marcha.|Art. 196.|Grave|5",
  "584-32|Deixar de indicar c/antec, med gesto de braço/luz indicadora, manobra de parar.|Art. 196.|Grave|5",
  "584-33|Deixar de indicar c/antec, med gesto de braço/luz indicadora, mudança direção.|Art. 196.|Grave|5",
  "584-34|Deixar de indicar c/antec, med gesto de braço/luz indicadora, mudança de faixa.|Art. 196.|Grave|5",
  "585-11|Deixar de deslocar c/antecedência veíc p/faixa mais à esquerda qdo for manobrar.|Art. 197.|Média|4",
  "585-12|Deixar de deslocar c/antecedência veíc p/faixa mais à direita qdo for manobrar.|Art. 197.|Média|4",
  "586-00|Deixar de dar passagem pela esquerda, quando solicitado.|Art. 198.|Média|4",
  "587-80|Ultrapassar pela direita, salvo quando o veículo da frente sinalizar que vai entrar à esquerda.|Art. 199.|Média|4",
  "588-60|Ultrap pela direita veíc transp colet/escolar parado para emb/desemb passageiros.|Art. 200.|Gravíssima|7",
  "589-40|Deixar de guardar a distância lateral de 1,50 m ao passar/ultrapassar bicicleta.|Art. 201.|Média|4",
  "590-80|Ultrapassar pelo acostamento.|Art. 202, I.|Gravíssima|7",
  "591-61|Ultrapassar em interseções.|Art. 202, II.|Gravíssima|7",
  "591-62|Ultrapassar em passagem de nível.|Art. 202, II.|Gravíssima|7",
  "592-41|Ultrapassar pela contramão nas curvas sem visibilidade suficiente.|Art. 203, I.|Gravíssima|7",
  "592-42|Ultrapassar pela contramão nos aclives ou declives, sem visibilidade suficiente.|Art. 203, I.|Gravíssima|7",
  "593-20|Ultrapassar pela contramão nas faixas de pedestre.|Art. 203, II.|Gravíssima|7",
  "594-01|Ultrapassar pela contramão nas pontes.|Art. 203, III.|Gravíssima|7",
  "594-02|Ultrapassar pela contramão nos viadutos.|Art. 203, III.|Gravíssima|7",
  "594-03|Ultrapassar pela contramão nos túneis.|Art. 203, III.|Gravíssima|7",
  "595-91|Ultrapassar pela contramão veículo parado em fila junto sinal luminoso.|Art. 203, IV.|Gravíssima|7",
  "595-92|Ultrapassar pela contramão veículo parado em fila junto a cancela/porteira.|Art. 203, IV.|Gravíssima|7",
  "595-93|Ultrapassar pela contramão veículo parado em fila junto a cruzamento.|Art. 203, IV.|Gravíssima|7",
  "595-94|Ultrapassar pela contramão veíc parado em fila junto qq impedimento à circulação.|Art. 203, IV.|Gravíssima|7",
  "596-70|Ultrapassar pela contramão linha de division de fluxos opostos, contínua amarela.|Art. 203, V.|Gravíssima|7",
  "597-50|Deixar de parar no acostamento à direita, p/ cruzar pista ou entrar à esquerda.|Art. 204.|Grave|5",
  "598-30|Ultrapassar veículo em movimento que integre cortejo/desfile/formação militar.|Art. 205.|Leve|3",
  "599-10|Executar operação de retorno em locais proibidos pela sinalização.|Art. 206, I.|Gravíssima|7",
  "600-91|Executar operação de retorno nas curvas.|Art. 206, II.|Gravíssima|7",
  "600-92|Executar operação de retorno nos aclives ou declives.|Art. 206, II.|Gravíssima|7",
  "600-93|Executar operação de retorno nas pontes.|Art. 206, II.|Gravíssima|7",
  "600-94|Executar operação de retorno nos viadutos.|Art. 206, II.|Gravíssima|7",
  "600-95|Executar operação de retorno nos túneis.|Art. 206, II.|Gravíssima|7",
  "601-71|Executar operação de retorno passando por cima de calçada, passeio.|Art. 206, III.|Gravíssima|7",
  "601-72|Executar operação de retorno passando por cima de ilha, refúgio.|Art. 206, III.|Gravíssima|7",
  "601-73|Executar operação de retorno passando por cima de ajardinamento.|Art. 206, III.|Gravíssima|7",
  "601-74|Executar operação de retorno passando por cima de canteiro de divisor de pista.|Art. 206, III.|Gravíssima|7",
  "601-75|Executar operação de retorno passando por cima de faixa de pedestres.|Art. 206, III.|Gravíssima|7",
  "601-76|Executar operação de retorno passando por cima de faixa de veíc não motorizados.|Art. 206, III.|Gravíssima|7",
  "602-50|Executar retorno nas interseções, entrando na contramão da via transversal.|Art. 206, IV.|Gravíssima|7",
  "603-30|Executar retorno c/prejuízo da circulação/segurança ainda que em local permitido.|Art. 206, V.|Gravíssima|7",
  "604-11|Executar operação de conversão à direita em local proibido pela sinalização.|Art. 207.|Grave|5",
  "604-12|Executar operação de conversão à esquerda em local proibido pela sinalização.|Art. 207.|Grave|5",
  "605-01|Avançar o sinal vermelho do semáforo, exc onde houver sinaliz que perm livre conv à direita.|Art. 208.|Gravíssima|7",
  "605-02|Avançar o sinal de parada obrigatória.|Art. 208.|Gravíssima|7",
  "606-81|Transpor bloqueio viário com ou sem sinalização ou dispositivos auxiliares.|Art. 209.|Grave|5",
  "606-82|Deixar de adentrar as áreas destinadas à pesagem de veículos.|Art. 209.|Grave|5",
  "606-85|Circular com eixos indevidamente suspensos os veículos de transporte de carga.|Art. 209.|Grave|5",
  "773-01|Evadir-se da cobrança pelo uso de rodovias e vias urbanas para não efetuar seu pagamento.|Art. 209-A.|Grave|5",
  "773-02|Deixar de efetuar pagamento, pelo uso de rodovias e vias urbanas, na forma estabelecida.|Art. 209-A.|Grave|5",
  "607-60|Transpor bloqueio viário policial.|Art. 210.|Gravíssima|7",
  "608-41|Ultrapassar veículos motorizados em fila, parados em razão de sinal luminoso.|Art. 211.|Grave|5",
  "608-42|Ultrapassar veículos motorizados em fila, parados em razão de cancela.|Art. 211.|Grave|5",
  "608-43|Ultrapassar veículos motorizados em fila parado em razão de bloqueio viário parcial.|Art. 211.|Grave|5",
  "608-44|Ultrapassar veículos motorizados em fila parado em razão de qualquer obstáculo.|Art. 211.|Grave|5",
  "609-20|Deixar de parar o veículo antes de transpor linha férrea.|Art. 212.|Gravíssima|7",
  "610-60|Deixar de parar o veículo sempre que a marcha for interceptada por agrupamento de pessoas.|Art. 213, I.|Gravíssima|7",
  "611-40|Deixar de parar o veículo sempre que a marcha for interceptada por agrupamento de veículos.|Art. 213, II.|Grave|5",
  "612-20|Deixar de dar preferência a pedestre/veic ñ motorizado na faixa a ele destinada.|Art. 214, I.|Gravíssima|7",
  "613-00|Deixar de dar preferência a pedestre/veic ñ mot que ñ haja concluído a travessia.|Art. 214, II.|Gravíssima|7",
  "614-90|Deixar de dar preferência a pedestre port deficiência fís/criança/idoso/gestante.|Art. 214, III.|Gravíssima|7",
  "615-70|Deixar de dar preferência a pedestre/veic ñ mot qdo iniciada travessia s/sinaliz.|Art. 214, IV.|Grave|5",
  "616-50|Deixar de dar preferência a pedestre/veic não mot atravessando a via transversal.|Art. 214, V.|Grave|5",
  "617-31|Deixar de dar preferência em interseção ñ sinaliz, a veíc circulando por rodovia.|Art. 215, I, a.|Grave|5",
  "617-32|Deixar de dar preferência em interseção ñ sinaliz, a veíc circulando por rotatória.|Art. 215, I, a.|Grave|5",
  "617-33|Deixar de dar prefer em interseção não sinalizada, a veículo que vier da direita.|Art. 215, I, b.|Grave|5",
  "618-10|Deixar de dar preferência nas interseções de Dê a Preferência.|Art. 215, II.|Grave|5",
  "619-00|Entrar/sair área lindeira sem precaução com a segurança de pedestres e veículos.|Art. 216.|Média|4",
  "620-30|Entrar/sair de fila de veículos estacionados sem dar pref a pedestres/veículos.|Art. 217.|Média|4",
  "745-50|Transitar em velocidade superior à máxima permitida em até 20%|Art. 218, I|Média|4",
  "746-30|Transitar em velocidade superior à máxima permitida em mais de 20% até 50%|Art. 218, II.|Grave|5",
  "747-10|Transitar em velocidade superior à máxima permitida em mais de 50%.|Art. 218, III.|Gravíssima|7",
  "625-40|Transitar em velocidade inferior à metade da máxima da via, salvo faixa direita.|Art. 219.|Média|4",
  "626-20|Deixar de reduzir a veloc qdo se aproximar de passeata/aglomeração/desfile/etc.|Art. 220, I.|Gravíssima|7",
  "627-00|Deixar de reduzir a veloc onde o trânsito esteja sendo controlado pelo agente.|Art. 220, II.|Grave|5",
  "628-91|Deixar de reduzir a velocidade do veículo ao aproximar-se da guia da calçada.|Art. 220, III.|Grave|5",
  "628-92|Deixar de reduzir a velocidade do veículo ao aproximar-se do acostamento.|Art. 220, III.|Grave|5",
  "629-70|Deixar de reduzir velocidade do veículo ao aproximar-se interseção ñ sinalizada.|Art. 220, IV.|Grave|5",
  "630-00|Deixar reduzir velocidade nas vias rurais cuja faixa de domínio não esteja cercada.|Art. 220, V.|Grave|5",
  "631-90|Deixar de reduzir a velocidade nos trechos em curva de pequeno raio.|Art. 220, VI.|Grave|5",
  "632-70|Deixar de reduzir veloc ao aproximar local sinaliz advert de obras/trabalhadores.|Art. 220, VII.|Grave|5",
  "633-50|Deixar de reduzir a velocidade sob chuva/neblina/cerração/ventos fortes.|Art. 220, VIII.|Grave|5",
  "634-30|Deixar de reduzir a velocidade quando houver má visibilidade.|Art. 220, IX.|Grave|5",
  "635-10|Deixar de reduzir veloc qdo pavimento se apresentar escorreg/defeituoso/avariado.|Art. 220, X.|Grave|5",
  "636-00|Deixar de reduzir a velocidade à aproximação de animais na pista.|Art. 220, XI.|Grave|5",
  "637-80|Deixar de reduzir a velocidade de forma compatível com a segurança em declive.|Art. 220, XII.|Grave|5",
  "638-60|Deixar de reduzir veloc de forma compatível c/ segurança ao ultrapassar ciclista.|Art. 220, XIII.|Gravíssima|7",
  "639-41|Deixar de reduzir a velocidade nas proximidades de escolas.|Art. 220, XIV.|Gravíssima|7",
  "639-42|Deixar de reduzir a velocidade nas proximidades de hospitais.|Art. 220, XIV.|Gravíssima|7",
  "639-43|Deixar de reduzir veloc na proxim estação embarque/desembarque passageiros.|Art. 220, XIV.|Gravíssima|7",
  "639-44|Deixar de reduzir veloc onde haja intensa movimentação de pedestres.|Art. 220, XIV.|Gravíssima|7",
  "640-80|Portar no veículo placas de identificação em desacordo c/ especif/modelo Contran.|Art. 221.|Média|4",
  "641-60|Confec/distribuir/colocar veíc próprio/terceiro placa identif desacordo Contran.|Art. 221, Parágrafo único.|Média|4",
  "642-40|Deixar de manter ligado em emerg sist ilum intermitente ainda q parado.|Art. 222.|Média|4",
  "643-21|Transitar com farol desregulado perturbando visão outro condutor.|Art. 223.|Grave|5",
  "643-22|Transitar com o facho de luz alta perturbando visão outro condutor.|Art. 223.|Grave|5",
  "644-00|Fazer uso do facho de luz alta dos faróis em vias providas de iluminação pública.|Art. 224.|Leve|3",
  "645-91|Deixar de sinalizar via p/ tornar visível local qdo tiver remover veíc da pista.|Art. 225, I.|Grave|5",
  "645-92|Deixar de sinalizar a via p/ tornar visível o local qdo permanecer acostamento.|Art. 225, I.|Grave|5",
  "646-70|Deixar de sinalizar a via p/ tornar visível o local qdo a carga for derramada.|Art. 225, II.|Grave|5",
  "647-50|Deixar de retirar qualquer objeto utilizado para sinalização temporária da via.|Art. 226.|Média|4",
  "648-30|Usar buzina que não a de toque breve como advertência a pedestre ou condutores.|Art. 227, I.|Leve|3",
  "649-10|Usar buzina prolongada e sucessivamente a qualquer pretexto.|Art. 227, II.|Leve|3",
  "650-50|Usar buzina entre as vinte e duas e às seis horas.|Art. 227, III.|Leve|3",
  "651-30|Usar buzina em locais e horários proibidos pela sinalização.|Art. 227, IV.|Leve|3",
  "652-10|Usar buzina em desacordo c/ os padrões e frequências estabelecidas pelo Contran.|Art. 227, V.|Leve|3",
  "653-00|Usar no veículo equip c/ som em volume/frequência não autorizados pelo Contran.|Art. 228.|Grave|5",
  "654-80|Usar no veíc alarme/aparelho produz som perturbe sossego pós desac norma Contran.|Art. 229.|Média|4",
  "655-61|Conduzir o veículo com o lacre de identificação violado/falsificado.|Art. 230, I.|Gravíssima|7",
  "655-62|Conduzir o veículo com a inscrição do chassi violada/falsificada.|Art. 230, I.|Gravíssima|7",
  "655-63|Conduzir o veículo como selo violado/falsificado.|Art. 230, I.|Gravíssima|7",
  "655-64|Conduzir o veículo com a placa violada/falsificada.|Art. 230, I.|Gravíssima|7",
  "655-65|Conduzir o veículo com qualquer outro elem de identificação violado/falsificado.|Art. 230, I.|Gravíssima|7",
  "656-40|Conduzir o veículo transportando passageiros em compartimento de carga.|Art. 230, II.|Gravíssima|7",
  "657-20|Conduzir o veículo com dispositivo antirradar.|Art. 230, III.|Gravíssima|7",
  "658-00|Conduzir o veículo sem qualquer uma das placas de identificação.|Art. 230, IV.|Gravíssima|7",
  "659-91|Conduzir o veículo que não esteja registrado.|Art. 230, V.|Gravíssima|7",
  "659-92|Conduzir o veículo registrado que não esteja devidamente licenciado.|Art. 230, V.|Gravíssima|7",
  "660-20|Conduzir o veículo com qualquer uma das placas sem legibilidade e visibilidade.|Art. 230, VI.|Gravíssima|7",
  "661-01|Conduzir o veículo com cor alterada.|Art. 230, VII.|Grave|5",
  "661-02|Conduzir o veículo com característica alterada.|Art. 230, VII.|Grave|5",
  "662-90|Conduzir veículo s/ ter sido submetido à inspeção seg veicular, qdo obrigatória.|Art. 230, VIII.|Grave|5",
  "663-71|Conduzir o veículo sem equipamento obrigatório.|Art. 230, IX.|Grave|5",
  "663-72|Conduzir o veículo com equipamento obrigatório ineficiente/inoperante.|Art. 230, IX.|Grave|5",
  "664-50|Conduzir o veículo com equip obrigatório em desacordo com o estab pelo Contran.|Art. 230, X.|Grave|5",
  "665-31|Conduzir o veículo com descarga livre.|Art. 230, XI.|Grave|5",
  "665-32|Conduzir o veículo com silenciador de motor de explosão defeituoso, deficiente ou inoperante.|Art. 230, XI.|Grave|5",
  "666-10|Conduzir o veículo com equipamento ou acessório proibido.|Art. 230, XII.|Grave|5",
  "667-00|Conduzir o veíc c/ equip do sistema de iluminação e de sinalização alterados.|Art. 230, XIII.|Grave|5",
  "668-80|Conduzir veíc c/ registrador instan inalt de velocidade/tempo viciado/defeituoso.|Art. 230, XIV.|Grave|5",
  "669-61|Conduzir c/ inscr/adesivo/legenda/símbolo afixado para-brisa e extensão traseira.|Art. 230, XV.|Grave|5",
  "669-62|Conduzir c/ inscr/adesivo/legenda/símbolo pintado para-brisa e extensão traseira.|Art. 230, XV.|Grave|5",
  "670-00|Conduzir o veíc com vidros total/parcialmente cobertos por película, painéis/pintura.|Art. 230, XVI.|Grave|5",
  "671-80|Conduzir o veículo com cortinas ou persianas fechadas.|Art. 230, XVII.|Grave|5",
  "672-61|Conduzir o veículo em mau estado de conservação, comprometendo a segurança.|Art. 230, XVIII.|Grave|5",
  "672-62|Conduzir o veículo reprovado na avaliação de inspeção de segurança.|Art. 230, XVIII.|Grave|5",
  "672-63|Conduzir o veículo reprovado na avaliação de emissão de poluentes e ruído.|Art. 230, XVIII.|Grave|5",
  "673-40|Conduzir o veículo sem acionar o limpador de para-brisa sob chuva.|Art. 230, XIX.|Grave|5",
  "674-20|Conduzir o veículo sem portar a autorização para condução de escolares.|Art. 230, XX.|Gravíssima|7",
  "675-00|Conduzir o veíc de carga c/ falta inscrição da tara e demais previstas no CTB.|Art. 230, XXI.|Média|4",
  "676-90|Conduzir veíc c/ defeito no sist de iluminação, sinaliz ou lâmpadas queimadas.|Art. 230, XXII.|Média|4",
  "756-00|Conduzir veíc de transp passag ou carga em desacordo c/ as cond do art 67-C CTB.|Art. 230, XXIII.|Média|4",
  "677-70|Transitar com o veículo danificando a via, suas instalações e equipamentos.|Art. 231, I.|Gravíssima|7",
  "678-51|Transitar com o veículo derramando a carga que esteja transportando.|Art. 231, II, a.|Gravíssima|7",
  "678-52|Transitar com veículo lançando a carga que esteja transportando.|Art. 231, II, a.|Gravíssima|7",
  "678-53|Transitar com veículo arrastando a carga que esteja transportando.|Art. 231, II, a.|Gravíssima|7",
  "679-30|Transitar com veíc derramando/lançando combustível/lubrif que esteja utilizando.|Art. 231, II, b.|Gravíssima|7",
  "680-70|Transitar c/ veíc derramando/lançando/arrastando qq objeto com risco de acidente.|Art. 231, II, c.|Gravíssima|7",
  "681-50|Transitar com veículo produzindo fumaça, gases ou partículas em desac c/ Contran.|Art. 231, III.|Grave|5",
  "682-31|Transitar c/ veíc e/ou carga c/ dimensões superiores limite legal s/autorização.|Art. 231, IV.|Grave|5",
  "682-32|Transitar c/ veíc e/ou carga c/dimensões superiores est p/sinalização s/autoriz.|Art. 231, IV.|Grave|5",
  "683-11|Transitar com o veículo com excesso de peso PBT/PBTC.|Art. 231, V.|Média|4",
  "683-12|Transitar com veículo com excesso de peso - por eixo.|Art. 231, V.|Média|4",
  "683-13|Transitar com o veículo com excesso de peso – PBT/PBTC e Por Eixo.|Art. 231, V.|Média|4",
  "684-01|Transitar em desacordo c/ autorização expedida p/veículo c/ dimensões excedentes.|Art. 231, VI.|Grave|5",
  "684-02|Transitar com autorização vencida, expedida para veículo com dimensões excedentes.|Art. 231, VI.|Grave|5",
  "685-80|Transitar com o veículo com lotação excedente.|Art. 231, VII.|Gravíssima|7",
  "686-61|Transitar efetuando transporte remunerado de pessoas qdo ñ licenciado p/esse fim.|Art. 231, VIII.|Gravíssima|7",
  "686-62|Transitar efetuando transporte remunerado de bens qdo não licenciado p/ esse fim.|Art. 231, VIII.|Gravíssima|7",
  "687-41|Transitar com veículo desligado em declive.|Art. 231, IX.|Média|4",
  "687-42|Transitar com veículo desengrenado em declive.|Art. 231, IX.|Média|4",
  "688-20|Transitar com o veículo excedendo a CMT em até 600kg.|Art. 231, X|Média|4",
  "689-00|Transitar com o veículo excedendo a CMT entre 601kg e 1000kg.|Art. 231, X.|Grave|5",
  "690-40|Transitar com o veículo excedendo a CMT acima de 1000kg.|Art. 231, X.|Gravíssima|7",
  "691-20|Conduzir veículo sem os documentos de porte obrigatório referidos no CTB.|Art. 232.|Leve|3",
  "692-01|Deixar de efetuar registro do veículo em 30 dias, qdo for transf a propriedade.|Art. 233 c/c 123, I.|Média|4",
  "692-02|Deixar de efetuar reg do veíc em 30 dias, qdo mudar o munic de domicílio/resid.|Art. 233 c/c 123, II.|Média|4",
  "692-03|Deixar de efetuar reg de veíc em 30 dias, qdo for alterada qquer caract do veíc.|Art. 233 c/c 123, III.|Média|4",
  "692-04|Deixar de efetuar registro de veic em 30 dias, qdo houver mudança de categoria.|Art. 233 c/c 123, IV.|Média|4",
  "693-91|Falsificar documento de habilitação.|Art. 234.|Gravíssima|7",
  "693-92|Falsificar ou adulterar documento de identificação do veículo.|Art. 234.|Gravíssima|7",
  "694-71|Conduzir pessoas nas partes externas do veículo.|Art. 235.|Grave|5",
  "694-72|Conduzir animais nas partes externas do veículo.|Art. 235.|Grave|5",
  "694-73|Conduzir carga nas partes externas do veículo.|Art. 235.|Grave|5",
  "695-50|Rebocar outro veículo com cabo flexível ou corda.|Art. 236.|Média|4",
  "696-30|Trans c/veíc desac c/especificação/falta de inscr/simbologia necessária identif.|Art. 237.|Grave|5",
  "697-10|Recusar-se a entregar CNH/CRV/CRLV/Outros documentos.|Art. 238.|Gravíssima|7",
  "698-00|Retirar do local veículo legalmente retido para regularização, sem permissão.|Art. 239.|Gravíssima|7",
  "699-80|Deixar responsável de promover baixa registro de veíc. irrecuperável/desmontado.|Art. 240.|Grave|5",
  "700-51|Deixar de atualizar o cadastro de registro do veículo.|Art. 241.|Leve|3",
  "700-52|Deixar de atualizar o cadastro de habilitação do condutor.|Art. 241.|Leve|3",
  "701-31|Fazer falsa declaração de domicílio para fins de registro/licenciamento.|Art. 242.|Gravíssima|7",
  "701-32|Fazer falsa declaração de domicílio para fins de habilitação.|Art. 242.|Gravíssima|7",
  "702-10|Deixar seguradora de comunicar ocorrência perda total veíc e devolver placas/doc.|Art. 243.|Grave|5",
  "712-92|Conduzir ciclomotor em via de trânsito rápido.|Art. 244, § 2º.|Média|4",
  "712-93|Conduzir ciclomotor em rodovia salvo se houver acostamento ou faixa própria.|Art. 244, § 2º.|Média|4",
  "703-01|Conduzir motocicleta, motoneta e ciclomotor sem capacete de segurança.|Art. 244, I.|Gravíssima|7",
  "703-03|Conduzir motocicleta, motoneta e ciclomotor sem vestuário aprovado pelo Contran.|Art. 244, I.|Gravíssima|7",
  "704-81|Conduzir motocicleta, motoneta e ciclomotor transportando passageiro sem capacete.|Art. 244, II.|Gravíssima|7",
  "704-83|Conduzir motocicleta, motoneta ou ciclomotor transportando passageiro fora do assento.|Art. 244, II.|Gravíssima|7",
  "705-61|Conduzir motocicleta, motoneta ou ciclomotor fazendo malabarismo ou equilibrando-se em uma roda.|Art. 244, III.|Gravíssima|7",
  "707-21|Conduzir motocicleta/motoneta/ciclomotor transportando criança menor de 10 anos de idade.|Art. 244, V.|Gravíssima|7",
  "707-22|Conduzir motoc/moton/ciclom transp criança s/ condição cuidar própria segurança.|Art. 244, V.|Gravíssima|7",
  "708-00|Conduzir motocicleta, motoneta ou ciclomotor rebocando outro veículo.|Art. 244, VI.|Grave|5",
  "709-91|Conduzir motocicleta/motoneta/ciclomotor sem segurar o guidom com ambas as mãos.|Art. 244, VII.|Grave|5",
  "710-21|Conduzir motocicleta, motoneta e ciclomotor transportando carga incompatível.|Art. 244, VIII.|Grave|5",
  "710-23|Conduzir motoc/moton/ transportando carga em desacordo c/ § 2º do Art 139-A CTB.|Art. 244, VIII.|Grave|5",
  "755-21|Conduzir motoc/moton/ efetuando transp remun mercadoria desac c/ art 139-A CTB.|Art. 244, IX.|Grave|5",
  "755-22|Conduzir motoc/moton/ efet transp remun desac normas ativid profic mototaxistas.|Art. 244, IX.|Grave|5",
  "768-41|Conduzir motoc/ moton/ ciclom c/ utilização de capacete de segurança s/ viseira/óculos de proteção.|Art. 244, X.|Média|4",
  "768-42|Conduzir motoc/ moton/ ciclom c/ útil capacete de seg c/ viseira/óculos prot em des c/ regul Contran.|Art. 244, X.|Média|4",
  "771-41|Conduzir motoc/ moton/ ciclom transp pass c/ capacete de segurança s/ viseira/óculos de proteção.|Art. 244, XI.|Média|4",
  "771-42|Conduzir motoc/ moton/ ciclom transp pass c/ cap seg c/ viseira/óculos prot em des c/ regul Contran.|Art. 244, XI.|Média|4",
  "714-50|Utilizar a via para depósito de mercadorias, materiais ou equipamentos.|Art. 245.|Grave|5",
  "715-31|Deixar de sinalizar obstáculo à circulação/segurança calçada/pista-s/agravamento|Art. 246.|Gravíssima|7",
  "715-32|Obstaculizar a via indevidamente-s/agravamento.|Art. 246.|Gravíssima|7",
  "716-11|Deixar de sinalizar obstáculo circulação/segurança calçada/pista-agravamento 2X.|Art. 246.|Gravíssima|7",
  "716-12|Obstaculizar a via indevidamente-agravamento 2X.|Art. 246.|Gravíssima|7",
  "717-01|Deixar de sinalizar obstáculo circulação/segurança calçada/pista-agravamento 3X.|Art. 246.|Gravíssima|7",
  "717-02|Obstaculizar a via indevidamente-agravamento 3X.|Art. 246.|Gravíssima|7",
  "718-81|Deixar de sinalizar obstáculo circulação/segurança calçada/pista-agravamento 4X.|Art. 246.|Gravíssima|7",
  "718-82|Obstaculizar a via indevidamente-agravamento 4X.|Art. 246.|Gravíssima|7",
  "719-61|Deixar de sinalizar obstáculo circulação/segurança calçada/pista-agravamento 5X.|Art. 246.|Gravíssima|7",
  "719-62|Obstaculizar a via indevidamente-agravamento 5X.|Art. 246.|Gravíssima|7",
  "720-01|Deixar de conduzir pelo bordo pista em fila única veíc tração/propulsão humana.|Art. 247.|Média|4",
  "720-02|Deixar de conduzir pelo bordo da pista em fila única veículo de tração animal.|Art. 247.|Média|4",
  "721-80|Transportar em veíc destinado transp passageiros carga excedente desac art.109.|Art. 248.|Grave|5",
  "722-61|Deixar de manter acesas à noite as luzes posição quando o veículo estiver parado.|Art. 249.|Média|4",
  "722-62|Deixar de manter acesas à noite as luzes de posição veic fazendo carga/descarga .|Art. 249.|Média|4",
  "723-40|Em movimento, deixar de manter acesa a luz baixa durante a noite.|Art. 250, I, a.|Média|4",
  "724-21|Em movimento de dia, deixar de manter acesa luz baixa em túneis.|Art. 250, I, b.|Média|4",
  "724-22|Em movimento de dia, deixar de manter acesa luz baixa sob chuva, neblina ou cerração.|Art. 250, I, b.|Média|4",
  "725-00|Em mov de dia, deixar de manter acesa luz baixa veíc transp coletivo faixas/pistas destinadas.|Art. 250, I, c.|Média|4",
  "726-90|Em movimento de dia, deixar de manter acesa luz baixa de motocicletas/motonetas/ ciclomotores.|Art. 250, I, d.|Média|4",
  "772-20|Em mov deix de man aces luz baixa de dia, em rod pis simp sit fora per urb, veíc desp luz rod diur|Art. 250, I, e.|Média|4",
  "728-50|Em movimento, deixar de manter a placa traseira iluminada à noite.|Art. 250, III.|Média|4",
  "775-71|Em movimento, deixar o veículo de transporte púb. coletivo passageiros de manter a porta fechada.|Art. 250, IV.|Gravíssima|7",
  "775-72|Em movimento, deixar o veículo de escolares de manter a porta fechada.|Art. 250, IV.|Gravíssima|7",
  "729-30|Utilizar o pisca-alerta, exceto em imobilizações ou situações de emergência.|Art. 251, I.|Média|4",
  "730-70|Utilizar luz alta e baixa intermitente, exceto quando permitido pelo CTB.|Art. 251, II.|Média|4",
  "763-31|Dirigir veículo segurando telefone celular.|Art. 252, parágrafo único.|Gravíssima|7",
  "763-32|Dirigir veículo manuseando telefone celular.|Art. 252, parágrafo único.|Gravíssima|7",
  "731-50|Dirigir o veículo com o braço do lado de fora.|Art. 252, I.|Média|4",
  "732-31|Dirigir o veículo transport pessoas à sua esquerda ou entre os braços e pernas.|Art. 252, II.|Média|4",
  "732-32|Dirigir o veículo transport animais à sua esquerda ou entre os braços e pernas.|Art. 252, II.|Média|4",
  "732-33|Dirigir o veículo transport volume à sua esquerda ou entre os braços e pernas.|Art. 252, II.|Média|4",
  "733-10|Dirigir o veículo com incapacidade física ou mental temporária.|Art. 252, III.|Média|4",
  "734-00|Dirigir o veíc usando calçado que ñ se firme nos pés/comprometa utiliz pedais.|Art. 252, IV.|Média|4",
  "735-80|Dirigir o veículo com apenas uma das mãos, exceto quando permitido pelo CTB.|Art. 252, V.|Média|4",
  "736-61|Dirigir o veículo utilizando-se de fones nos ouvidos conec a aparelhagem sonora.|Art. 252, VI.|Média|4",
  "736-62|Dirigir veículo utilizando-se de telefone celular.|Art. 252, VI.|Média|4",
  "759-50|Dirigir veículo realizando cobrança de tarifa com veículo em movimento.|Art. 252, VII.|Média|4",
  "737-40|Bloquear a via com veículo.|Art. 253.|Gravíssima|7",
  "761-71|Usar veículo para, deliberadamente, interromper a circulação na via.|Art. 253-A.|Gravíssima|7",
  "761-72|Usar veículo para, deliberadamente, restringir a circulação na via.|Art. 253-A.|Gravíssima|7",
  "761-73|Usar veículo para, deliberadamente, perturbar a circulação na via.|Art. 253-A.|Gravíssima|7",
  "760-90|Organizar as condutas previstas no caput do art. 253-A.|Art. 253-A, §1º.|Gravíssima|7",
  "776-50|Fugir do condutor à ação policial.|Art. 278, § único.|Gravíssima|7",
  "754-41|Falta de escrituração livro registro entrada/saída e de uso placa de experiência.|Art. 330, § 5º.|Gravíssima|7",
  "754-42|Atraso escrituração livro registro entrada/saída e de uso placa de experiência.|Art. 330, § 5º.|Gravíssima|7",
  "754-43|Fraude escrituração livro registro entrada/saída e de uso placa de experiência.|Art. 330, § 5º.|Gravíssima|7",
  "754-44|Recusa da exibição do livro registro entrada/saída e de uso placa de experiência.|Art. 330, § 5º.|Gravíssima|7"
];

// Helper to expand and calculate values
export const DEFAULT_INFRACTIONS: InfractionType[] = RAW_INFRACTIONS.map((raw) => {
  const [code, description, framing, nature, scoreStr] = raw.split('|');
  const score = parseInt(scoreStr, 10) || 0;
  
  // Calculate CTB standardized values (R$)
  let fineValue = 0;
  let natureVal: 'Leve' | 'Média' | 'Grave' | 'Gravíssima' = 'Média';

  if (nature === 'Gravíssima') {
    natureVal = 'Gravíssima';
    fineValue = 293.47;
    // Multipliers for extreme cases
    if (code === '501-00' || code === '516-91' || code === '757-90' || code === '524-00' || code === '525-81' || code === '525-82' || code === '525-83' || code === '526-61' || code === '526-62' || code === '526-63' || code === '527-41' || code === '527-42' || code === '579-70' || code === '761-71' || code === '761-72' || code === '761-73' || code === '760-90') {
      fineValue = code === '516-91' || code === '757-90' || code === '761-71' || code === '761-72' || code === '761-73' || code === '760-90' ? 2934.70 : 1467.35;
    }
  } else if (nature === 'Grave') {
    natureVal = 'Grave';
    fineValue = 195.23;
  } else if (nature === 'Média') {
    natureVal = 'Média';
    fineValue = 130.16;
  } else {
    natureVal = 'Leve';
    fineValue = 88.38;
  }

  // Map standardized CTB administrative measures
  let adminMeasure = 'Nenhuma';
  if (code.startsWith('501-') || code.startsWith('508-') || code.startsWith('511-') || code.startsWith('513-') || code.startsWith('514-')) {
    adminMeasure = 'Retenção do veículo até a apresentação de condutor habilitado';
  } else if (code.startsWith('542-') || code.startsWith('543-') || code.startsWith('545-') || code.startsWith('546-') || code.startsWith('548-') || code.startsWith('551-')) {
    adminMeasure = 'Remoção do veículo';
  } else if (code === '516-91' || code === '516-92' || code === '757-90') {
    adminMeasure = 'Retenção do veículo, recolhimento da CNH e suspensão do direito de dirigir por 12 meses';
  } else if (code.startsWith('502-') || code.startsWith('512-')) {
    adminMeasure = 'Recolhimento do documento de habilitação e retenção do veículo';
  } else if (code.startsWith('518-')) {
    adminMeasure = 'Retenção do veículo até colocação do cinto pelo infrator';
  }

  return {
    code,
    description,
    framing: framing + ' do CTB',
    article: framing.replace('Art.', '').replace('.', '').trim(),
    nature: natureVal,
    fineValue,
    score,
    adminMeasure
  };
});
